use hackathon2;

INSERT INTO hackathon2.data (id, mot, count) VALUES (7, 'test', 71);
INSERT INTO hackathon2.data (id, mot, count) VALUES (8, 'code', 6);
INSERT INTO hackathon2.data (id, mot, count) VALUES (36, 'ceci', 35);
INSERT INTO hackathon2.data (id, mot, count) VALUES (39, 'peau', 19);
INSERT INTO hackathon2.data (id, mot, count) VALUES (40, 'visage', 19);
INSERT INTO hackathon2.data (id, mot, count) VALUES (41, 'seche', 19);

INSERT INTO hackathon2.user (id, email, password) VALUES (1, 'admin@gmail.com', '$argon2id$v=19$m=19456,t=2,p=1$Neox+TGRGFrOoOG/cV3PnA$tvfWPpXdKLMebWBi+o7S90oL7lLu0/1XMD4fom7owLM');

INSERT INTO hackathon2.blacklist (id, mot) VALUES (2, 'la');
INSERT INTO hackathon2.blacklist (id, mot) VALUES (3, 'les');
INSERT INTO hackathon2.blacklist (id, mot) VALUES (4, 'un');
INSERT INTO hackathon2.blacklist (id, mot) VALUES (5, 'une');
INSERT INTO hackathon2.blacklist (id, mot) VALUES (6, 'des');
INSERT INTO hackathon2.blacklist (id, mot) VALUES (7, 'du');
INSERT INTO hackathon2.blacklist (id, mot) VALUES (8, 'de');
INSERT INTO hackathon2.blacklist (id, mot) VALUES (9, 'd\'');
INSERT INTO hackathon2.blacklist (id, mot) VALUES (10, 'l\'');
INSERT INTO hackathon2.blacklist (id, mot) VALUES (11, 'et');
INSERT INTO hackathon2.blacklist (id, mot) VALUES (12, 'ou');
INSERT INTO hackathon2.blacklist (id, mot) VALUES (13, 'où');
INSERT INTO hackathon2.blacklist (id, mot) VALUES (14, 'à');
INSERT INTO hackathon2.blacklist (id, mot) VALUES (15, 'a');
INSERT INTO hackathon2.blacklist (id, mot) VALUES (16, 'au');
INSERT INTO hackathon2.blacklist (id, mot) VALUES (17, 'aux');
INSERT INTO hackathon2.blacklist (id, mot) VALUES (18, 'en');
INSERT INTO hackathon2.blacklist (id, mot) VALUES (19, 'dans');
INSERT INTO hackathon2.blacklist (id, mot) VALUES (20, 'par');
INSERT INTO hackathon2.blacklist (id, mot) VALUES (21, 'pour');
INSERT INTO hackathon2.blacklist (id, mot) VALUES (22, 'sur');
INSERT INTO hackathon2.blacklist (id, mot) VALUES (23, 'sous');
INSERT INTO hackathon2.blacklist (id, mot) VALUES (24, 'vers');
INSERT INTO hackathon2.blacklist (id, mot) VALUES (25, 'avec');
INSERT INTO hackathon2.blacklist (id, mot) VALUES (26, 'sans');
INSERT INTO hackathon2.blacklist (id, mot) VALUES (27, 'chez');
INSERT INTO hackathon2.blacklist (id, mot) VALUES (28, 'entre');
INSERT INTO hackathon2.blacklist (id, mot) VALUES (29, 'mais');
INSERT INTO hackathon2.blacklist (id, mot) VALUES (30, 'donc');
INSERT INTO hackathon2.blacklist (id, mot) VALUES (31, 'or');
INSERT INTO hackathon2.blacklist (id, mot) VALUES (32, 'ni');
INSERT INTO hackathon2.blacklist (id, mot) VALUES (33, 'car');
INSERT INTO hackathon2.blacklist (id, mot) VALUES (34, 'que');
INSERT INTO hackathon2.blacklist (id, mot) VALUES (35, 'qui');
INSERT INTO hackathon2.blacklist (id, mot) VALUES (36, 'quoi');
INSERT INTO hackathon2.blacklist (id, mot) VALUES (37, 'quand');
INSERT INTO hackathon2.blacklist (id, mot) VALUES (38, 'comment');
INSERT INTO hackathon2.blacklist (id, mot) VALUES (39, 'pourquoi');
INSERT INTO hackathon2.blacklist (id, mot) VALUES (40, 'combien');
INSERT INTO hackathon2.blacklist (id, mot) VALUES (41, 'quel');
INSERT INTO hackathon2.blacklist (id, mot) VALUES (42, 'quelle');
INSERT INTO hackathon2.blacklist (id, mot) VALUES (43, 'quels');
INSERT INTO hackathon2.blacklist (id, mot) VALUES (44, 'quelles');
INSERT INTO hackathon2.blacklist (id, mot) VALUES (45, 'si');
INSERT INTO hackathon2.blacklist (id, mot) VALUES (46, 'comme');
INSERT INTO hackathon2.blacklist (id, mot) VALUES (47, 'lorsque');
INSERT INTO hackathon2.blacklist (id, mot) VALUES (48, 'lorsqu\'');
INSERT INTO hackathon2.blacklist (id, mot) VALUES (49, 'lors');
INSERT INTO hackathon2.blacklist (id, mot) VALUES (50, 'puisque');
INSERT INTO hackathon2.blacklist (id, mot) VALUES (51, 'quoique');
INSERT INTO hackathon2.blacklist (id, mot) VALUES (52, 'afin');
INSERT INTO hackathon2.blacklist (id, mot) VALUES (53, 'alors');
INSERT INTO hackathon2.blacklist (id, mot) VALUES (54, 'aussi');
INSERT INTO hackathon2.blacklist (id, mot) VALUES (55, 'autant');
INSERT INTO hackathon2.blacklist (id, mot) VALUES (56, 'autre');
INSERT INTO hackathon2.blacklist (id, mot) VALUES (57, 'autres');
INSERT INTO hackathon2.blacklist (id, mot) VALUES (58, 'autrement');
INSERT INTO hackathon2.blacklist (id, mot) VALUES (59, 'autour');
INSERT INTO hackathon2.blacklist (id, mot) VALUES (60, 'autrefois');
INSERT INTO hackathon2.blacklist (id, mot) VALUES (61, 'autrui');
INSERT INTO hackathon2.blacklist (id, mot) VALUES (62, 'avant');
INSERT INTO hackathon2.blacklist (id, mot) VALUES (63, 'avec');
INSERT INTO hackathon2.blacklist (id, mot) VALUES (64, 'bien');
INSERT INTO hackathon2.blacklist (id, mot) VALUES (65, 'bientôt');
INSERT INTO hackathon2.blacklist (id, mot) VALUES (263, 'le');
INSERT INTO hackathon2.blacklist (id, mot) VALUES (264, 'est');
INSERT INTO hackathon2.blacklist (id, mot) VALUES (265, 'j\'ai');
